### ISSUE TITLE
CheckBox inside ToolBar has wrong vertical alignment of the check box and foreground color

### ISSUE THREAD

**Issue by silviubogan** [steto-scope/Monotone#2]
If I put these lines inside the ToolBar [here](https://github.com/steto-scope/Monotone/blob/master/Monotone/MainWindow.xaml#L64):

```xaml
<CheckBox Style="{StaticResource {x:Type CheckBox}}">
    test
</CheckBox>
```

I get these results:

**With mouse not over:**

![2019-07-18_16-33-28](https://user-images.githubusercontent.com/198924/61461681-dae3a600-a979-11e9-95ea-fd8a6f561e28.png)

**With mouse over:**

![2019-07-18_16-32-36](https://user-images.githubusercontent.com/198924/61461688-de772d00-a979-11e9-8c06-c17399670b61.png)

# A partial solution

If I put ` VerticalAlignment="Center" ` in [this line](https://github.com/steto-scope/Monotone/blob/master/Monotone/Monotone.xaml#L156) the check box aligns well, but the foreground color is still too dark when hovering the CheckBox with the mouse.

**Comment by steto-scope** [comment]
Fixed
