### ISSUE TITLE
Include a Style for the WPF RepeatButton

### ISSUE THREAD

**Issue by silviubogan** [steto-scope/Monotone#3]
I think all that has to be done is to copy-paste [these lines](https://github.com/steto-scope/Monotone/blob/master/Monotone/Monotone.xaml#L56-L92) and replace Button with RepeatButton in the TargetType attribute of the ControlTemplate and Style.

**Comment by steto-scope** [comment]
I haven't noticed that this style was missing, thanks for mentioning it. 
Committed to master
